/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.opl-page[_ngcontent-%COMP%] {\n    background-color: #ffffff;\n    margin: 20px 0px;\n}\n.opl-cell[_ngcontent-%COMP%] {\n    display: flex;\n    align-items: center;\n    padding: 15px;\n    border-bottom: 1px solid #efefef;\n}\n.opl-cell[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\n    flex: 1;\n}\n.opl-cell[_ngcontent-%COMP%]   mat-icon[_ngcontent-%COMP%]::before{\n    content: "\\f077";\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL3JvdXRlcy91c2VyLXByb2ZpbGUvdXNlci1wcm9maWxlLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvcm91dGVzL3VzZXItcHJvZmlsZS91c2VyLXByb2ZpbGUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
