/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.index-banner[_ngcontent-%COMP%] {\n	display: inline-block;\n	width: 100%;\n	height: auto;\n}\n\n.faq-title[_ngcontent-%COMP%] {\n	background-color: #eff2f7;\n	color: #a7b8d2;\n	font-size: 16px;\n	height: 40px;\n	vertical-align: middle;\n	border-radius: 2px;\n	position: relative;\n	cursor: pointer;\n}\n.faq-title[_ngcontent-%COMP%]:hover {\n	background-color: #bbc9e0;\n	color: #a7b8d2;\n	font-size: 16px;\n	height: 40px;\n	vertical-align: middle;\n	border-radius: 2px;\n	position: relative;\n	cursor: pointer;\n}\n\n.faq-title-num[_ngcontent-%COMP%] {\n	display: inline-block;\n	width: 50px;\n	border-top-right-radius: 50%;\n	border-bottom-right-radius: 50%;\n	background-color: #a7b8d2;\n	color: #fff;\n	text-align: center;\n	line-height: 40px;\n	vertical-align: 40px;\n	float: left;\n}\n\n.faq-title-content[_ngcontent-%COMP%] {\n	color: #ffbf41;\n	font-size: 14px;\n	text-align: left;\n}\n\n.faq-content[_ngcontent-%COMP%] {\n	margin: 10px auto 10px 10px;\n	color: #5e5e5e;\n	font-size: 14px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2hvbWUvZmFxL2ZhcS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2hvbWUvZmFxL2ZhcS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
