/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './login.module';
import * as i2 from './login.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/cdk/bidi';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/cdk/platform';
import * as i8 from '@angular/cdk/observers';
import * as i9 from '@angular/cdk/scrolling';
import * as i10 from '@angular/material/core';
import * as i11 from '@angular/cdk/overlay';
import * as i12 from '@angular/material/select';
import * as i13 from '@angular/cdk/a11y';
import * as i14 from '@angular/material/icon';
import * as i15 from '@angular/http';
import * as i16 from '@angular/material/stepper';
import * as i17 from '@angular/router';
import * as i18 from './login-routing.module';
import * as i19 from '../../layout/layout.module';
import * as i20 from '@angular/cdk/portal';
import * as i21 from '@angular/material/tabs';
import * as i22 from '@angular/material/form-field';
import * as i23 from '@angular/material/input';
import * as i24 from '@angular/material/button';
import * as i25 from '@angular/material/card';
import * as i26 from '@angular/cdk/stepper';
import * as i27 from './login.component';
export const LoginModuleNgFactory:i0.NgModuleFactory<i1.LoginModule> = i0.ɵcmf(i1.LoginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LoginComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i4.FormBuilder,i4.FormBuilder,
              ([] as any[])),i0.ɵmpd(6144,i5.DIR_DOCUMENT,(null as any),[i6.DOCUMENT]),
          i0.ɵmpd(4608,i5.Directionality,i5.Directionality,[[2,i5.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i7.Platform,i7.Platform,([] as any[])),i0.ɵmpd(4608,i8.MatMutationObserverFactory,
              i8.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(5120,i9.ScrollDispatcher,
              i9.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i9.ScrollDispatcher],i0.NgZone,
                  i7.Platform]),i0.ɵmpd(5120,i9.ViewportRuler,i9.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i9.ViewportRuler],i7.Platform,i0.NgZone,i9.ScrollDispatcher]),i0.ɵmpd(4608,
              i10.ErrorStateMatcher,i10.ErrorStateMatcher,([] as any[])),i0.ɵmpd(4608,
              i11.ScrollStrategyOptions,i11.ScrollStrategyOptions,[i9.ScrollDispatcher,
                  i9.ViewportRuler]),i0.ɵmpd(5120,i11.OverlayContainer,i11.ɵa,[[3,
              i11.OverlayContainer]]),i0.ɵmpd(4608,i11.ɵf,i11.ɵf,[i9.ViewportRuler]),
          i0.ɵmpd(4608,i11.Overlay,i11.Overlay,[i11.ScrollStrategyOptions,i11.OverlayContainer,
              i0.ComponentFactoryResolver,i11.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),
          i0.ɵmpd(5120,i11.ɵc,i11.ɵd,[i11.Overlay]),i0.ɵmpd(5120,i12.MAT_SELECT_SCROLL_STRATEGY,
              i12.MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,[i11.Overlay]),i0.ɵmpd(4608,
              i13.InteractivityChecker,i13.InteractivityChecker,[i7.Platform]),i0.ɵmpd(4608,
              i13.FocusTrapFactory,i13.FocusTrapFactory,[i13.InteractivityChecker,
                  i7.Platform,i0.NgZone]),i0.ɵmpd(136192,i13.AriaDescriber,i13.ARIA_DESCRIBER_PROVIDER_FACTORY,
              [[3,i13.AriaDescriber],i7.Platform]),i0.ɵmpd(5120,i13.LiveAnnouncer,
              i13.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i13.LiveAnnouncer],[2,i13.LIVE_ANNOUNCER_ELEMENT_TOKEN],
                  i7.Platform]),i0.ɵmpd(5120,i13.FocusMonitor,i13.FOCUS_MONITOR_PROVIDER_FACTORY,
              [[3,i13.FocusMonitor],i0.NgZone,i7.Platform]),i0.ɵmpd(5120,i14.MatIconRegistry,
              i14.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i14.MatIconRegistry],[2,i15.Http],
                  i6.DomSanitizer]),i0.ɵmpd(4608,i16.MatStepperIntl,i16.MatStepperIntl,
              ([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),
          i0.ɵmpd(512,i17.RouterModule,i17.RouterModule,[[2,i17.ɵa],[2,i17.Router]]),
          i0.ɵmpd(512,i18.LoginRoutingModule,i18.LoginRoutingModule,([] as any[])),
          i0.ɵmpd(512,i19.LayoutModule,i19.LayoutModule,([] as any[])),i0.ɵmpd(512,
              i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,i4.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i10.CompatibilityModule,i10.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i5.BidiModule,i5.BidiModule,([] as any[])),
          i0.ɵmpd(256,i10.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i10.MatCommonModule,
              i10.MatCommonModule,[[2,i10.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i20.PortalModule,
              i20.PortalModule,([] as any[])),i0.ɵmpd(512,i7.PlatformModule,i7.PlatformModule,
              ([] as any[])),i0.ɵmpd(512,i10.MatRippleModule,i10.MatRippleModule,([] as any[])),
          i0.ɵmpd(512,i8.ObserversModule,i8.ObserversModule,([] as any[])),i0.ɵmpd(512,
              i9.ScrollDispatchModule,i9.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i21.MatTabsModule,i21.MatTabsModule,([] as any[])),i0.ɵmpd(512,i22.MatFormFieldModule,
              i22.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i23.MatInputModule,
              i23.MatInputModule,([] as any[])),i0.ɵmpd(512,i11.OverlayModule,i11.OverlayModule,
              ([] as any[])),i0.ɵmpd(512,i10.MatPseudoCheckboxModule,i10.MatPseudoCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i10.MatOptionModule,i10.MatOptionModule,([] as any[])),
          i0.ɵmpd(512,i12.MatSelectModule,i12.MatSelectModule,([] as any[])),i0.ɵmpd(512,
              i13.A11yModule,i13.A11yModule,([] as any[])),i0.ɵmpd(512,i24.MatButtonModule,
              i24.MatButtonModule,([] as any[])),i0.ɵmpd(512,i25.MatCardModule,i25.MatCardModule,
              ([] as any[])),i0.ɵmpd(512,i26.CdkStepperModule,i26.CdkStepperModule,
              ([] as any[])),i0.ɵmpd(512,i14.MatIconModule,i14.MatIconModule,([] as any[])),
          i0.ɵmpd(512,i16.MatStepperModule,i16.MatStepperModule,([] as any[])),i0.ɵmpd(512,
              i1.LoginModule,i1.LoginModule,([] as any[])),i0.ɵmpd(1024,i17.ROUTES,
              () => {
                return [[{path:'',component:i27.LoginComponent},{path:'login',component:i27.LoginComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL3JvdXRlcy9sb2dpbi9sb2dpbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvcm91dGVzL2xvZ2luL2xvZ2luLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
