/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './header.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header.component';
const styles_HeaderComponent:any[] = [i0.styles];
export const RenderType_HeaderComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HeaderComponent,data:{}});
export function View_HeaderComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  header works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_HeaderComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-header',
      ([] as any[]),(null as any),(null as any),(null as any),View_HeaderComponent_0,
      RenderType_HeaderComponent)),i1.ɵdid(1,114688,(null as any),0,i2.HeaderComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HeaderComponentNgFactory:i1.ComponentFactory<i2.HeaderComponent> = i1.ɵccf('app-header',
    i2.HeaderComponent,View_HeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9oZWFkZXIvaGVhZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9sYXlvdXQvaGVhZGVyL2hlYWRlci5jb21wb25lbnQudHMiLCJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9sYXlvdXQvaGVhZGVyL2hlYWRlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9oZWFkZXIvaGVhZGVyLmNvbXBvbmVudC50cy5IZWFkZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgaGVhZGVyIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsNENBRUM7TUFBQTs7O29CQ0ZKO01BQUE7Z0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
