/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.material-icons.md-18[_ngcontent-%COMP%] { font-size: 18px; }\n.panel-title[_ngcontent-%COMP%] { font-size: 14px; }\n.panel-detail[_ngcontent-%COMP%] { font-size: 10px; }\n[_nghost-%COMP%]     p { font-size: 10px }\n\nimg[_ngcontent-%COMP%] {\n	width: 100%;\n  }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2hvbWUvY2hhbm5lbC1pbnRyby9jaGFubmVsLWludHJvLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvaG9tZS9jaGFubmVsLWludHJvL2NoYW5uZWwtaW50cm8uY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
