/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './spinner.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './spinner.component';
import * as i4 from '../../core/service/common.service';
const styles_SpinnerComponent:any[] = [i0.styles];
export const RenderType_SpinnerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SpinnerComponent,data:{}});
function View_SpinnerComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),6,'div',[['class',
      'spinner-container']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(2,
      0,(null as any),(null as any),3,'div',[['class','circles-container']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
      (null as any),['\n    '])),(_l()(),i1.ɵeld(4,0,(null as any),(null as any),0,
      'img',[['src','/assets/images/loading.gif']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_SpinnerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_SpinnerComponent_1)),i1.ɵdid(2,
      16384,(null as any),0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,
      _v) => {
    var _co:i3.SpinnerComponent = _v.component;
    const currVal_0:any = _co.isSpinnerShow;
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_SpinnerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-spinner',
      ([] as any[]),(null as any),(null as any),(null as any),View_SpinnerComponent_0,
      RenderType_SpinnerComponent)),i1.ɵdid(1,114688,(null as any),0,i3.SpinnerComponent,
      [i4.CommonService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SpinnerComponentNgFactory:i1.ComponentFactory<i3.SpinnerComponent> = i1.ɵccf('app-spinner',
    i3.SpinnerComponent,View_SpinnerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9zcGlubmVyL3NwaW5uZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9zcGlubmVyL3NwaW5uZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvbGF5b3V0L3NwaW5uZXIvc3Bpbm5lci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9zcGlubmVyL3NwaW5uZXIuY29tcG9uZW50LnRzLlNwaW5uZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8IS0tIDxkaXYgY2xhc3M9XCJzcGlubmVyLWNvbnRhaW5lclwiIG5nLXNob3c9XCJpc1NwaW5uZXJTaG93XCI+IC0tPlxuPGRpdiBjbGFzcz1cInNwaW5uZXItY29udGFpbmVyXCIgKm5nSWY9XCJpc1NwaW5uZXJTaG93XCI+XG4gIDxkaXYgY2xhc3M9XCJjaXJjbGVzLWNvbnRhaW5lclwiPlxuICAgIDxpbWcgc3JjPVwiL2Fzc2V0cy9pbWFnZXMvbG9hZGluZy5naWZcIj5cbiAgPC9kaXY+XG48L2Rpdj5cbiIsIjxhcHAtc3Bpbm5lcj48L2FwcC1zcGlubmVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NBO01BQUE7TUFBQSxnQkFBcUQsNENBQ25EO01BQUE7TUFBQSwwREFBK0I7TUFBQSwyQkFDN0I7TUFBQTtNQUFBLDhCQUFzQyw0Q0FDbEM7YUFBQTs7O29CQUp3RCwwQ0FDaEU7TUFBQSw2RUFBQTtNQUFBO1VBQUEsd0JBSU07OztJQUp5QjtJQUEvQixXQUErQixTQUEvQjs7OztvQkNEQTtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
