/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.spinner-container[_ngcontent-%COMP%] {\n    background-color: rgba(255, 255, 255, .8);\n    opacity: 0.6;\n    bottom: 0;\n    display: block;\n    left: 0;\n    position: fixed;\n    right: 0;\n    top: 0;\n    z-index: 10000;\n   \n}\n\n\n.image-container[_ngcontent-%COMP%] {\n    background-color: rgba(255, 255, 255, .8);\n    opacity: 1;\n    bottom: 0;\n    display: block;\n    left: 0;\n    position: fixed;\n    right: 0;\n    top: 0;\n    z-index: 10000;\n   \n}\n.image-container[_ngcontent-%COMP%]   .circles-container[_ngcontent-%COMP%]{\n    z-index: 10000;\n    left: 20%;\n    margin-left: -16px;\n    position: fixed;\n    top: 10%;\n   \n}\n.image-container[_ngcontent-%COMP%]   .circles-container[_ngcontent-%COMP%]   img[_ngcontent-%COMP%]{\n    width: 100px;\n    height: 100px;\n}\n .circles-container[_ngcontent-%COMP%] {\n      z-index: 10000;\n        left: 40%;\n        margin-left: -16px;\n        position: fixed;\n        top: 20%;\n    }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2xheW91dC9zcGlubmVyL3NwaW5uZXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9sYXlvdXQvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
