/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './order.module';
import * as i2 from './order-list/order-list.component.ngfactory';
import * as i3 from './order-detail/order-detail.component.ngfactory';
import * as i4 from './order-tracking/order-tracking.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/forms';
import * as i7 from '@angular/cdk/platform';
import * as i8 from '@angular/material/core';
import * as i9 from '@angular/cdk/bidi';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/cdk/a11y';
import * as i12 from '@angular/material/icon';
import * as i13 from '@angular/http';
import * as i14 from '@angular/material/stepper';
import * as i15 from '@angular/cdk/observers';
import * as i16 from '../layout/layout.module';
import * as i17 from '@angular/material/form-field';
import * as i18 from '@angular/material/input';
import * as i19 from '@angular/router';
import * as i20 from './order-routing.module';
import * as i21 from '@angular/cdk/portal';
import * as i22 from '@angular/material/button';
import * as i23 from '@angular/cdk/stepper';
import * as i24 from '@angular/material/checkbox';
import * as i25 from './order-list/order-list.component';
import * as i26 from './order-detail/order-detail.component';
import * as i27 from './order-tracking/order-tracking.component';
export const OrderModuleNgFactory:i0.NgModuleFactory<i1.OrderModule> = i0.ɵcmf(i1.OrderModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.OrderListComponentNgFactory,i3.OrderDetailComponentNgFactory,i4.OrderTrackingComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.NgLocalization,
          i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),
          i0.ɵmpd(4608,i7.Platform,i7.Platform,([] as any[])),i0.ɵmpd(4608,i8.ErrorStateMatcher,
              i8.ErrorStateMatcher,([] as any[])),i0.ɵmpd(6144,i9.DIR_DOCUMENT,(null as any),
              [i10.DOCUMENT]),i0.ɵmpd(4608,i9.Directionality,i9.Directionality,[[2,
              i9.DIR_DOCUMENT]]),i0.ɵmpd(4608,i11.InteractivityChecker,i11.InteractivityChecker,
              [i7.Platform]),i0.ɵmpd(4608,i11.FocusTrapFactory,i11.FocusTrapFactory,
              [i11.InteractivityChecker,i7.Platform,i0.NgZone]),i0.ɵmpd(136192,i11.AriaDescriber,
              i11.ARIA_DESCRIBER_PROVIDER_FACTORY,[[3,i11.AriaDescriber],i7.Platform]),
          i0.ɵmpd(5120,i11.LiveAnnouncer,i11.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i11.LiveAnnouncer],
              [2,i11.LIVE_ANNOUNCER_ELEMENT_TOKEN],i7.Platform]),i0.ɵmpd(5120,i11.FocusMonitor,
              i11.FOCUS_MONITOR_PROVIDER_FACTORY,[[3,i11.FocusMonitor],i0.NgZone,i7.Platform]),
          i0.ɵmpd(5120,i12.MatIconRegistry,i12.ICON_REGISTRY_PROVIDER_FACTORY,[[3,
              i12.MatIconRegistry],[2,i13.Http],i10.DomSanitizer]),i0.ɵmpd(4608,i14.MatStepperIntl,
              i14.MatStepperIntl,([] as any[])),i0.ɵmpd(4608,i15.MatMutationObserverFactory,
              i15.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(512,i5.CommonModule,
              i5.CommonModule,([] as any[])),i0.ɵmpd(512,i16.LayoutModule,i16.LayoutModule,
              ([] as any[])),i0.ɵmpd(512,i6.ɵba,i6.ɵba,([] as any[])),i0.ɵmpd(512,
              i6.FormsModule,i6.FormsModule,([] as any[])),i0.ɵmpd(512,i7.PlatformModule,
              i7.PlatformModule,([] as any[])),i0.ɵmpd(512,i17.MatFormFieldModule,
              i17.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i18.MatInputModule,
              i18.MatInputModule,([] as any[])),i0.ɵmpd(512,i19.RouterModule,i19.RouterModule,
              [[2,i19.ɵa],[2,i19.Router]]),i0.ɵmpd(512,i20.OrderRoutingModule,i20.OrderRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i8.CompatibilityModule,i8.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i9.BidiModule,i9.BidiModule,([] as any[])),
          i0.ɵmpd(256,i8.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i8.MatCommonModule,
              i8.MatCommonModule,[[2,i8.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i21.PortalModule,
              i21.PortalModule,([] as any[])),i0.ɵmpd(512,i8.MatRippleModule,i8.MatRippleModule,
              ([] as any[])),i0.ɵmpd(512,i11.A11yModule,i11.A11yModule,([] as any[])),
          i0.ɵmpd(512,i22.MatButtonModule,i22.MatButtonModule,([] as any[])),i0.ɵmpd(512,
              i23.CdkStepperModule,i23.CdkStepperModule,([] as any[])),i0.ɵmpd(512,
              i12.MatIconModule,i12.MatIconModule,([] as any[])),i0.ɵmpd(512,i14.MatStepperModule,
              i14.MatStepperModule,([] as any[])),i0.ɵmpd(512,i15.ObserversModule,
              i15.ObserversModule,([] as any[])),i0.ɵmpd(512,i24.MatCheckboxModule,
              i24.MatCheckboxModule,([] as any[])),i0.ɵmpd(512,i1.OrderModule,i1.OrderModule,
              ([] as any[])),i0.ɵmpd(1024,i19.ROUTES,() => {
            return [[{path:'',component:i25.OrderListComponent},{path:'order-detail/:orderNumber',
                component:i26.OrderDetailComponent},{path:'tracking',component:i27.OrderTrackingComponent},
                {path:'tracking/:trackingNumber',component:i27.OrderTrackingComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
