/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './order-routing.module';
import * as i2 from './order-list/order-list.component.ngfactory';
import * as i3 from './order-detail/order-detail.component.ngfactory';
import * as i4 from './order-tracking/order-tracking.component.ngfactory';
import * as i5 from '@angular/router';
import * as i6 from './order-list/order-list.component';
import * as i7 from './order-detail/order-detail.component';
import * as i8 from './order-tracking/order-tracking.component';
export const OrderRoutingModuleNgFactory:i0.NgModuleFactory<i1.OrderRoutingModule> = i0.ɵcmf(i1.OrderRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.OrderListComponentNgFactory,i3.OrderDetailComponentNgFactory,i4.OrderTrackingComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,i5.RouterModule,
          i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i1.OrderRoutingModule,
          i1.OrderRoutingModule,([] as any[])),i0.ɵmpd(1024,i5.ROUTES,() => {
        return [[{path:'',component:i6.OrderListComponent},{path:'order-detail/:orderNumber',
            component:i7.OrderDetailComponent},{path:'tracking',component:i8.OrderTrackingComponent},
            {path:'tracking/:trackingNumber',component:i8.OrderTrackingComponent}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
