/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './order.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from './order.component';
const styles_OrderComponent:any[] = [i0.styles];
export const RenderType_OrderComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_OrderComponent,data:{}});
export function View_OrderComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(1,212992,(null as any),0,i2.RouterOutlet,[i2.ChildrenOutletContexts,
          i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n\n']))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export function View_OrderComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-order',
      ([] as any[]),(null as any),(null as any),(null as any),View_OrderComponent_0,
      RenderType_OrderComponent)),i1.ɵdid(1,114688,(null as any),0,i3.OrderComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const OrderComponentNgFactory:i1.ComponentFactory<i3.OrderComponent> = i1.ɵccf('app-order',
    i3.OrderComponent,View_OrderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci5jb21wb25lbnQudHMiLCJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLmNvbXBvbmVudC50cy5PcmRlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cblxuPCEtLSAyMzIzIC0tPiIsIjxhcHAtb3JkZXI+PC9hcHAtb3JkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7MERBQUE7VUFBQSw2QkFBK0I7O1FBQS9COzs7O29CQ0FBO01BQUE7K0JBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
