/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './order.module';
import * as i2 from './order-list/order-list.component.ngfactory';
import * as i3 from './order-detail/order-detail.component.ngfactory';
import * as i4 from './order-tracking/order-tracking.component.ngfactory';
import * as i5 from '@angular/material/snack-bar/typings/index.ngfactory';
import * as i6 from '@angular/common';
import * as i7 from '@angular/forms';
import * as i8 from '@angular/cdk/platform';
import * as i9 from '@angular/material/core';
import * as i10 from '@angular/cdk/bidi';
import * as i11 from '@angular/platform-browser';
import * as i12 from '@angular/cdk/a11y';
import * as i13 from '@angular/material/icon';
import * as i14 from '@angular/http';
import * as i15 from '@angular/material/stepper';
import * as i16 from '@angular/cdk/observers';
import * as i17 from '@angular/cdk/scrolling';
import * as i18 from '@angular/cdk/overlay';
import * as i19 from '@angular/material/snack-bar';
import * as i20 from '../layout/layout.module';
import * as i21 from '@angular/material/form-field';
import * as i22 from '@angular/material/input';
import * as i23 from '@angular/router';
import * as i24 from './order-routing.module';
import * as i25 from '@angular/cdk/portal';
import * as i26 from '@angular/material/button';
import * as i27 from '@angular/cdk/stepper';
import * as i28 from '@angular/material/checkbox';
import * as i29 from './order-list/order-list.component';
import * as i30 from './order-detail/order-detail.component';
import * as i31 from './order-tracking/order-tracking.component';
export const OrderModuleNgFactory:i0.NgModuleFactory<i1.OrderModule> = i0.ɵcmf(i1.OrderModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.OrderListComponentNgFactory,i3.OrderDetailComponentNgFactory,i4.OrderTrackingComponentNgFactory,
              i5.MatSnackBarContainerNgFactory,i5.SimpleSnackBarNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),i0.ɵmpd(4608,i8.Platform,
          i8.Platform,([] as any[])),i0.ɵmpd(4608,i9.ErrorStateMatcher,i9.ErrorStateMatcher,
          ([] as any[])),i0.ɵmpd(6144,i10.DIR_DOCUMENT,(null as any),[i11.DOCUMENT]),
          i0.ɵmpd(4608,i10.Directionality,i10.Directionality,[[2,i10.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i12.InteractivityChecker,i12.InteractivityChecker,[i8.Platform]),
          i0.ɵmpd(4608,i12.FocusTrapFactory,i12.FocusTrapFactory,[i12.InteractivityChecker,
              i8.Platform,i0.NgZone]),i0.ɵmpd(136192,i12.AriaDescriber,i12.ARIA_DESCRIBER_PROVIDER_FACTORY,
              [[3,i12.AriaDescriber],i8.Platform]),i0.ɵmpd(5120,i12.LiveAnnouncer,
              i12.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i12.LiveAnnouncer],[2,i12.LIVE_ANNOUNCER_ELEMENT_TOKEN],
                  i8.Platform]),i0.ɵmpd(5120,i12.FocusMonitor,i12.FOCUS_MONITOR_PROVIDER_FACTORY,
              [[3,i12.FocusMonitor],i0.NgZone,i8.Platform]),i0.ɵmpd(5120,i13.MatIconRegistry,
              i13.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i13.MatIconRegistry],[2,i14.Http],
                  i11.DomSanitizer]),i0.ɵmpd(4608,i15.MatStepperIntl,i15.MatStepperIntl,
              ([] as any[])),i0.ɵmpd(4608,i16.MatMutationObserverFactory,i16.MatMutationObserverFactory,
              ([] as any[])),i0.ɵmpd(5120,i17.ScrollDispatcher,i17.SCROLL_DISPATCHER_PROVIDER_FACTORY,
              [[3,i17.ScrollDispatcher],i0.NgZone,i8.Platform]),i0.ɵmpd(5120,i17.ViewportRuler,
              i17.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i17.ViewportRuler],i8.Platform,
                  i0.NgZone,i17.ScrollDispatcher]),i0.ɵmpd(4608,i18.ScrollStrategyOptions,
              i18.ScrollStrategyOptions,[i17.ScrollDispatcher,i17.ViewportRuler]),
          i0.ɵmpd(5120,i18.OverlayContainer,i18.ɵa,[[3,i18.OverlayContainer]]),i0.ɵmpd(4608,
              i18.ɵf,i18.ɵf,[i17.ViewportRuler]),i0.ɵmpd(4608,i18.Overlay,i18.Overlay,
              [i18.ScrollStrategyOptions,i18.OverlayContainer,i0.ComponentFactoryResolver,
                  i18.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i18.ɵc,
              i18.ɵd,[i18.Overlay]),i0.ɵmpd(4608,i19.MatSnackBar,i19.MatSnackBar,[i18.Overlay,
              i12.LiveAnnouncer,i0.Injector,[3,i19.MatSnackBar]]),i0.ɵmpd(512,i6.CommonModule,
              i6.CommonModule,([] as any[])),i0.ɵmpd(512,i20.LayoutModule,i20.LayoutModule,
              ([] as any[])),i0.ɵmpd(512,i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,
              i7.FormsModule,i7.FormsModule,([] as any[])),i0.ɵmpd(512,i8.PlatformModule,
              i8.PlatformModule,([] as any[])),i0.ɵmpd(512,i21.MatFormFieldModule,
              i21.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i22.MatInputModule,
              i22.MatInputModule,([] as any[])),i0.ɵmpd(512,i23.RouterModule,i23.RouterModule,
              [[2,i23.ɵa],[2,i23.Router]]),i0.ɵmpd(512,i24.OrderRoutingModule,i24.OrderRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i9.CompatibilityModule,i9.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i10.BidiModule,i10.BidiModule,([] as any[])),
          i0.ɵmpd(256,i9.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i9.MatCommonModule,
              i9.MatCommonModule,[[2,i9.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i25.PortalModule,
              i25.PortalModule,([] as any[])),i0.ɵmpd(512,i9.MatRippleModule,i9.MatRippleModule,
              ([] as any[])),i0.ɵmpd(512,i12.A11yModule,i12.A11yModule,([] as any[])),
          i0.ɵmpd(512,i26.MatButtonModule,i26.MatButtonModule,([] as any[])),i0.ɵmpd(512,
              i27.CdkStepperModule,i27.CdkStepperModule,([] as any[])),i0.ɵmpd(512,
              i13.MatIconModule,i13.MatIconModule,([] as any[])),i0.ɵmpd(512,i15.MatStepperModule,
              i15.MatStepperModule,([] as any[])),i0.ɵmpd(512,i16.ObserversModule,
              i16.ObserversModule,([] as any[])),i0.ɵmpd(512,i28.MatCheckboxModule,
              i28.MatCheckboxModule,([] as any[])),i0.ɵmpd(512,i17.ScrollDispatchModule,
              i17.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i18.OverlayModule,
              i18.OverlayModule,([] as any[])),i0.ɵmpd(512,i19.MatSnackBarModule,i19.MatSnackBarModule,
              ([] as any[])),i0.ɵmpd(512,i1.OrderModule,i1.OrderModule,([] as any[])),
          i0.ɵmpd(1024,i23.ROUTES,() => {
            return [[{path:'',component:i29.OrderListComponent},{path:'order-detail/:orderNumber',
                component:i30.OrderDetailComponent},{path:'tracking',component:i31.OrderTrackingComponent},
                {path:'tracking/:trackingNumber',component:i31.OrderTrackingComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
