/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ote-page[_ngcontent-%COMP%] {\n    text-align: center;\n    padding: 30px 10px;\n}\n.ote-page[_ngcontent-%COMP%]   img[_ngcontent-%COMP%]{\n    width: 50%;\n}\n\n.ote-page[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{\n    font-size: 20px;\n    color: #607eae;\n}\n\n.ote-page[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]{\n    font-size: 15px;\n    color: #999999;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvb3JkZXIvb3JkZXItdHJhY2tpbmcvb3JkZXItbm8tdHJhY2tpbmcvb3JkZXItbm8tdHJhY2tpbmcuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
