/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './order-no-tracking.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './order-no-tracking.component';
const styles_OrderNoTrackingComponent:any[] = [i0.styles];
export const RenderType_OrderNoTrackingComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_OrderNoTrackingComponent,data:{}});
export function View_OrderNoTrackingComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),15,'div',[['class',
      'ote-page']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(2,0,(null as any),
          (null as any),3,'div',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i1.ɵeld(4,0,(null as any),(null as any),0,'img',[['src','/assets/images/no-page.png']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n  '])),(_l()(),i1.ɵeld(7,0,(null as any),(null as any),7,'div',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(9,0,(null as any),
          (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['无效的运单号码...'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(12,0,(null as any),
          (null as any),1,'span',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['您输入的运单号码有误，别着急，核对一下您的运单号码再输一次试试。'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_OrderNoTrackingComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-order-no-tracking',
      ([] as any[]),(null as any),(null as any),(null as any),View_OrderNoTrackingComponent_0,
      RenderType_OrderNoTrackingComponent)),i1.ɵdid(1,114688,(null as any),0,i2.OrderNoTrackingComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const OrderNoTrackingComponentNgFactory:i1.ComponentFactory<i2.OrderNoTrackingComponent> = i1.ɵccf('app-order-no-tracking',
    i2.OrderNoTrackingComponent,View_OrderNoTrackingComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci10cmFja2luZy9vcmRlci1uby10cmFja2luZy9vcmRlci1uby10cmFja2luZy5jb21wb25lbnQudHMiLCJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci10cmFja2luZy9vcmRlci1uby10cmFja2luZy9vcmRlci1uby10cmFja2luZy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nL29yZGVyLW5vLXRyYWNraW5nLmNvbXBvbmVudC50cy5PcmRlck5vVHJhY2tpbmdDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwib3RlLXBhZ2VcIj5cbiAgPGRpdj5cbiAgICA8aW1nIHNyYz1cIi9hc3NldHMvaW1hZ2VzL25vLXBhZ2UucG5nXCI+XG4gIDwvZGl2PlxuICA8ZGl2PlxuICAgIDxwPuaXoOaViOeahOi/kOWNleWPt+eggS4uLjwvcD5cbiAgICA8c3Bhbj7mgqjovpPlhaXnmoTov5DljZXlj7fnoIHmnInor6/vvIzliKvnnYDmgKXvvIzmoLjlr7nkuIDkuIvmgqjnmoTov5DljZXlj7fnoIHlho3ovpPkuIDmrKHor5Xor5XjgII8L3NwYW4+XG4gIDwvZGl2PlxuPC9kaXY+IiwiPGFwcC1vcmRlci1uby10cmFja2luZz48L2FwcC1vcmRlci1uby10cmFja2luZz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFzQiw0Q0FDcEI7VUFBQTtVQUFBLDhCQUFLO01BQ0g7VUFBQTtNQUFzQyw0Q0FDbEM7VUFBQSxXQUNOO1VBQUE7TUFBSyw4Q0FDSDtVQUFBO1VBQUEsOEJBQUc7TUFBYyw4Q0FDakI7VUFBQTtVQUFBLDhCQUFNO01BQXVDLDRDQUN6QztVQUFBOzs7b0JDUFI7TUFBQTt5Q0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
