/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.opl-page[_ngcontent-%COMP%] {\n    background-color: #ffffff;\n    margin: 20px 0px;\n}\n.opl-cell[_ngcontent-%COMP%] {\n    display: flex;\n    align-items: center;\n    padding: 15px;\n    border-bottom: 1px solid #efefef;\n}\n.opl-cell[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\n    flex: 1;\n}\n.opl-cell[_ngcontent-%COMP%]   mat-icon[_ngcontent-%COMP%]::before{\n    content: "\\f077";\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLXBhY2thZ2UtbGlzdC9vcmRlci1wYWNrYWdlLWxpc3QuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci10cmFja2luZy9vcmRlci1wYWNrYWdlLWxpc3Qvb3JkZXItcGFja2FnZS1saXN0LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
