/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './layout/spinner/spinner.component.ngfactory';
import * as i3 from './layout/spinner/spinner.component';
import * as i4 from './core/service/common.service';
import * as i5 from '@angular/router';
import * as i6 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n\n'])),(_l()(),i1.ɵeld(1,
      0,(null as any),(null as any),1,'app-spinner',([] as any[]),(null as any),(null as any),
      (null as any),i2.View_SpinnerComponent_0,i2.RenderType_SpinnerComponent)),i1.ɵdid(2,
      114688,(null as any),0,i3.SpinnerComponent,[i4.CommonService],(null as any),
      (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(4,16777216,
      (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),i1.ɵdid(5,212992,(null as any),0,
      i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
          [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any))],(_ck,
      _v) => {
    _ck(_v,2,0);
    _ck(_v,5,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i6.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i6.AppComponent> = i1.ɵccf('app-root',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cbjxhcHAtc3Bpbm5lcj48L2FwcC1zcGlubmVyPlxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsNENBRUE7TUFBQTtNQUFBLGlGQUFBO01BQUE7TUFBQSxlQUEyQiwwQ0FDM0I7TUFBQTtNQUFBLG1EQUFBO3NCQUFBO1VBQUE7O0lBREE7SUFDQTs7OztvQkNIQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
