/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './routes/user-profile/user-profile.component.ngfactory';
import * as i4 from './routes/login/login.component.ngfactory';
import * as i5 from './order/order-list/order-list.component.ngfactory';
import * as i6 from './order/order-detail/order-detail.component.ngfactory';
import * as i7 from './order/order-tracking/order-tracking.component.ngfactory';
import * as i8 from './home/channel-intro/channel-intro.component.ngfactory';
import * as i9 from './home/embargo/embargo.component.ngfactory';
import * as i10 from './home/howtouse/howtouse.component.ngfactory';
import * as i11 from './home/faq/faq.component.ngfactory';
import * as i12 from './home/about/about.component.ngfactory';
import * as i13 from './home/terms/terms.component.ngfactory';
import * as i14 from './home/terms/terms-en/terms-en.component.ngfactory';
import * as i15 from './home/terms/appendix-limit/appendix-limit.component.ngfactory';
import * as i16 from './home/terms/appendix-ormd/appendix-ormd.component.ngfactory';
import * as i17 from './home/terms/insurance-intro/insurance-intro.component.ngfactory';
import * as i18 from './app.component.ngfactory';
import * as i19 from '@angular/common';
import * as i20 from '@angular/platform-browser';
import * as i21 from '@angular/animations/browser';
import * as i22 from '@angular/platform-browser/animations';
import * as i23 from '@angular/animations';
import * as i24 from '@angular/forms';
import * as i25 from '@angular/http';
import * as i26 from '@angular/router';
import * as i27 from '@angular/cdk/bidi';
import * as i28 from '@angular/cdk/platform';
import * as i29 from '@angular/cdk/observers';
import * as i30 from '@angular/cdk/scrolling';
import * as i31 from '@angular/material/core';
import * as i32 from '@angular/cdk/overlay';
import * as i33 from '@angular/material/select';
import * as i34 from '@angular/cdk/a11y';
import * as i35 from '@angular/material/icon';
import * as i36 from '@angular/material/stepper';
import * as i37 from './core/service/storage.service';
import * as i38 from './core/service/auth.service';
import * as i39 from 'angular2-jwt/angular2-jwt';
import * as i40 from './core/core.module';
import * as i41 from './core/service/common.service';
import * as i42 from './core/service/commonwx.service';
import * as i43 from './core/service/user.service';
import * as i44 from './core/service/guards/auth-guard.service';
import * as i45 from './core/service/order.service';
import * as i46 from './core/service/common-api.service';
import * as i47 from '@angular/cdk/collections';
import * as i48 from './routes/user-profile/user-profile.component';
import * as i49 from './routes/login/login.component';
import * as i50 from './order/order-list/order-list.component';
import * as i51 from './order/order-detail/order-detail.component';
import * as i52 from './order/order-tracking/order-tracking.component';
import * as i53 from './home/channel-intro/channel-intro.component';
import * as i54 from './home/embargo/embargo.component';
import * as i55 from './home/howtouse/howtouse.component';
import * as i56 from './home/faq/faq.component';
import * as i57 from './home/about/about.component';
import * as i58 from './home/terms/terms.component';
import * as i59 from './home/terms/terms-en/terms-en.component';
import * as i60 from './home/terms/appendix-limit/appendix-limit.component';
import * as i61 from './home/terms/appendix-ormd/appendix-ormd.component';
import * as i62 from './home/terms/insurance-intro/insurance-intro.component';
import * as i63 from './app-routing.module';
import * as i64 from './routes/login/login-routing.module';
import * as i65 from './layout/layout.module';
import * as i66 from '@angular/cdk/portal';
import * as i67 from '@angular/material/tabs';
import * as i68 from '@angular/material/form-field';
import * as i69 from '@angular/material/input';
import * as i70 from '@angular/material/button';
import * as i71 from '@angular/material/card';
import * as i72 from '@angular/cdk/stepper';
import * as i73 from './routes/login/login.module';
import * as i74 from './order/order-routing.module';
import * as i75 from '@angular/material/checkbox';
import * as i76 from './order/order.module';
import * as i77 from './core/service/pipes/pipes.module';
import * as i78 from '@angular/material/expansion';
import * as i79 from '@angular/material/grid-list';
import * as i80 from './home/home-routing.module';
import * as i81 from './home/home.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.UserProfileComponentNgFactory,i4.LoginComponentNgFactory,i5.OrderListComponentNgFactory,
              i6.OrderDetailComponentNgFactory,i7.OrderTrackingComponentNgFactory,
              i8.ChannelIntroComponentNgFactory,i9.EmbargoComponentNgFactory,i10.HowtouseComponentNgFactory,
              i11.FaqComponentNgFactory,i12.AboutComponentNgFactory,i13.TermsComponentNgFactory,
              i14.TermsEnComponentNgFactory,i15.AppendixLimitComponentNgFactory,i16.AppendixOrmdComponentNgFactory,
              i17.InsuranceIntroComponentNgFactory,i18.AppComponentNgFactory]],[3,
              i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i19.NgLocalization,i19.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i20.DomSanitizer,i20.ɵe,[i19.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i20.DomSanitizer]),i0.ɵmpd(4608,
              i20.HAMMER_GESTURE_CONFIG,i20.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i20.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i20.ɵDomEventsPlugin(p0_0),new i20.ɵKeyEventsPlugin(p1_0),
                    new i20.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i19.DOCUMENT,i19.DOCUMENT,i19.DOCUMENT,i20.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i20.EventManager,i20.EventManager,[i20.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i20.ɵDomSharedStylesHost,i20.ɵDomSharedStylesHost,
              [i19.DOCUMENT]),i0.ɵmpd(4608,i20.ɵDomRendererFactory2,i20.ɵDomRendererFactory2,
              [i20.EventManager,i20.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i21.AnimationDriver,
              i22.ɵc,([] as any[])),i0.ɵmpd(5120,i21.ɵAnimationStyleNormalizer,i22.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i21.ɵAnimationEngine,i22.ɵb,[i21.AnimationDriver,
              i21.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i22.ɵe,
              [i20.ɵDomRendererFactory2,i21.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i20.ɵSharedStylesHost,(null as any),[i20.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i20.Meta,i20.Meta,
              [i19.DOCUMENT]),i0.ɵmpd(4608,i20.Title,i20.Title,[i19.DOCUMENT]),i0.ɵmpd(4608,
              i23.AnimationBuilder,i22.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
                  i20.DOCUMENT]),i0.ɵmpd(4608,i24.ɵi,i24.ɵi,([] as any[])),i0.ɵmpd(4608,
              i25.BrowserXhr,i25.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i25.ResponseOptions,
              i25.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i25.XSRFStrategy,
              i25.ɵb,([] as any[])),i0.ɵmpd(4608,i25.XHRBackend,i25.XHRBackend,[i25.BrowserXhr,
              i25.ResponseOptions,i25.XSRFStrategy]),i0.ɵmpd(4608,i25.RequestOptions,
              i25.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i25.Http,i25.ɵc,[i25.XHRBackend,
              i25.RequestOptions]),i0.ɵmpd(5120,i26.ActivatedRoute,i26.ɵf,[i26.Router]),
          i0.ɵmpd(4608,i26.NoPreloading,i26.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i26.PreloadingStrategy,(null as any),[i26.NoPreloading]),i0.ɵmpd(135680,
              i26.RouterPreloader,i26.RouterPreloader,[i26.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i26.PreloadingStrategy]),i0.ɵmpd(4608,i26.PreloadAllModules,
              i26.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i26.ROUTER_INITIALIZER,
              i26.ɵi,[i26.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i26.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i24.FormBuilder,i24.FormBuilder,
              ([] as any[])),i0.ɵmpd(6144,i27.DIR_DOCUMENT,(null as any),[i20.DOCUMENT]),
          i0.ɵmpd(4608,i27.Directionality,i27.Directionality,[[2,i27.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i28.Platform,i28.Platform,([] as any[])),i0.ɵmpd(4608,i29.MatMutationObserverFactory,
              i29.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(5120,i30.ScrollDispatcher,
              i30.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i30.ScrollDispatcher],i0.NgZone,
                  i28.Platform]),i0.ɵmpd(5120,i30.ViewportRuler,i30.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i30.ViewportRuler],i28.Platform,i0.NgZone,i30.ScrollDispatcher]),
          i0.ɵmpd(4608,i31.ErrorStateMatcher,i31.ErrorStateMatcher,([] as any[])),
          i0.ɵmpd(4608,i32.ScrollStrategyOptions,i32.ScrollStrategyOptions,[i30.ScrollDispatcher,
              i30.ViewportRuler]),i0.ɵmpd(5120,i32.OverlayContainer,i32.ɵa,[[3,i32.OverlayContainer]]),
          i0.ɵmpd(4608,i32.ɵf,i32.ɵf,[i30.ViewportRuler]),i0.ɵmpd(4608,i32.Overlay,
              i32.Overlay,[i32.ScrollStrategyOptions,i32.OverlayContainer,i0.ComponentFactoryResolver,
                  i32.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i32.ɵc,
              i32.ɵd,[i32.Overlay]),i0.ɵmpd(5120,i33.MAT_SELECT_SCROLL_STRATEGY,i33.MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i32.Overlay]),i0.ɵmpd(4608,i34.InteractivityChecker,i34.InteractivityChecker,
              [i28.Platform]),i0.ɵmpd(4608,i34.FocusTrapFactory,i34.FocusTrapFactory,
              [i34.InteractivityChecker,i28.Platform,i0.NgZone]),i0.ɵmpd(136192,i34.AriaDescriber,
              i34.ARIA_DESCRIBER_PROVIDER_FACTORY,[[3,i34.AriaDescriber],i28.Platform]),
          i0.ɵmpd(5120,i34.LiveAnnouncer,i34.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i34.LiveAnnouncer],
              [2,i34.LIVE_ANNOUNCER_ELEMENT_TOKEN],i28.Platform]),i0.ɵmpd(5120,i34.FocusMonitor,
              i34.FOCUS_MONITOR_PROVIDER_FACTORY,[[3,i34.FocusMonitor],i0.NgZone,i28.Platform]),
          i0.ɵmpd(5120,i35.MatIconRegistry,i35.ICON_REGISTRY_PROVIDER_FACTORY,[[3,
              i35.MatIconRegistry],[2,i25.Http],i20.DomSanitizer]),i0.ɵmpd(4608,i36.MatStepperIntl,
              i36.MatStepperIntl,([] as any[])),i0.ɵmpd(4608,i37.StorageService,i37.StorageService,
              ([] as any[])),i0.ɵmpd(4608,i38.AuthService,i38.AuthService,[i37.StorageService,
              i26.Router]),i0.ɵmpd(5120,i39.AuthHttp,i40.authFactory,[i25.Http,i25.RequestOptions]),
          i0.ɵmpd(4608,i41.CommonService,i41.CommonService,[i25.Http,i39.AuthHttp,
              i38.AuthService]),i0.ɵmpd(4608,i42.CommonwxService,i42.CommonwxService,
              [i25.Http,i39.AuthHttp]),i0.ɵmpd(4608,i43.UserService,i43.UserService,
              [i41.CommonService,i42.CommonwxService]),i0.ɵmpd(4608,i44.AuthGuardService,
              i44.AuthGuardService,[i26.ActivatedRoute,i38.AuthService,i43.UserService,
                  i26.Router]),i0.ɵmpd(4608,i45.OrderService,i45.OrderService,[i41.CommonService]),
          i0.ɵmpd(4608,i46.CommonApiService,i46.CommonApiService,[i41.CommonService]),
          i0.ɵmpd(5120,i47.UniqueSelectionDispatcher,i47.ɵa,[[3,i47.UniqueSelectionDispatcher]]),
          i0.ɵmpd(512,i19.CommonModule,i19.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i20.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i26.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i26.ɵg,i26.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i20.ɵc(p0_0,p0_1),i26.ɵh(p1_0)];
              },[[2,i20.NgProbeToken],[2,i0.NgProbeToken],i26.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i20.BrowserModule,i20.BrowserModule,[[3,i20.BrowserModule]]),
          i0.ɵmpd(512,i22.BrowserAnimationsModule,i22.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i24.ɵba,i24.ɵba,([] as any[])),i0.ɵmpd(512,i24.FormsModule,i24.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i25.HttpModule,i25.HttpModule,([] as any[])),
          i0.ɵmpd(1024,i26.ɵa,i26.ɵd,[[3,i26.Router]]),i0.ɵmpd(512,i26.UrlSerializer,
              i26.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i26.ChildrenOutletContexts,
              i26.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i26.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i19.LocationStrategy,i26.ɵc,[i19.PlatformLocation,
              [2,i19.APP_BASE_HREF],i26.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i19.Location,
              i19.Location,[i19.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i26.ROUTES,
              () => {
                return [[{path:'login',loadChildren:'./routes/login/login.module#LoginModule'},
                    {path:'order',canLoad:[i44.AuthGuardService],loadChildren:'./order/order.module#OrderModule'},
                    {path:'home',loadChildren:'./home/home.module#HomeModule'},{path:'user-profile',
                        canActivate:[i44.AuthGuardService],component:i48.UserProfileComponent}],
                    [{path:'',component:i49.LoginComponent},{path:'login',component:i49.LoginComponent}],
                    [{path:'',component:i50.OrderListComponent},{path:'order-detail/:orderNumber',
                        component:i51.OrderDetailComponent},{path:'tracking',component:i52.OrderTrackingComponent},
                        {path:'tracking/:trackingNumber',component:i52.OrderTrackingComponent}],
                    [{path:'channel-intro',component:i53.ChannelIntroComponent},{path:'embargo',
                        component:i54.EmbargoComponent},{path:'howtouse',component:i55.HowtouseComponent},
                        {path:'faq',component:i56.FaqComponent},{path:'about',component:i57.AboutComponent},
                        {path:'terms',component:i58.TermsComponent},{path:'terms-en',
                            component:i59.TermsEnComponent},{path:'appendix-limit',
                            component:i60.AppendixLimitComponent},{path:'appendix-ormd',
                            component:i61.AppendixOrmdComponent},{path:'insurance-intro',
                            component:i62.InsuranceIntroComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i26.Router,i26.ɵe,[i0.ApplicationRef,i26.UrlSerializer,
              i26.ChildrenOutletContexts,i19.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i26.ROUTES,i26.ROUTER_CONFIGURATION,[2,i26.UrlHandlingStrategy],
              [2,i26.RouteReuseStrategy]]),i0.ɵmpd(512,i26.RouterModule,i26.RouterModule,
              [[2,i26.ɵa],[2,i26.Router]]),i0.ɵmpd(512,i63.AppRoutingModule,i63.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i64.LoginRoutingModule,i64.LoginRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i65.LayoutModule,i65.LayoutModule,([] as any[])),
          i0.ɵmpd(512,i24.ReactiveFormsModule,i24.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i31.CompatibilityModule,i31.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i27.BidiModule,i27.BidiModule,([] as any[])),i0.ɵmpd(256,i31.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i31.MatCommonModule,i31.MatCommonModule,
              [[2,i31.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i66.PortalModule,i66.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i28.PlatformModule,i28.PlatformModule,([] as any[])),
          i0.ɵmpd(512,i31.MatRippleModule,i31.MatRippleModule,([] as any[])),i0.ɵmpd(512,
              i29.ObserversModule,i29.ObserversModule,([] as any[])),i0.ɵmpd(512,i30.ScrollDispatchModule,
              i30.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i67.MatTabsModule,
              i67.MatTabsModule,([] as any[])),i0.ɵmpd(512,i68.MatFormFieldModule,
              i68.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i69.MatInputModule,
              i69.MatInputModule,([] as any[])),i0.ɵmpd(512,i32.OverlayModule,i32.OverlayModule,
              ([] as any[])),i0.ɵmpd(512,i31.MatPseudoCheckboxModule,i31.MatPseudoCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i31.MatOptionModule,i31.MatOptionModule,([] as any[])),
          i0.ɵmpd(512,i33.MatSelectModule,i33.MatSelectModule,([] as any[])),i0.ɵmpd(512,
              i34.A11yModule,i34.A11yModule,([] as any[])),i0.ɵmpd(512,i70.MatButtonModule,
              i70.MatButtonModule,([] as any[])),i0.ɵmpd(512,i71.MatCardModule,i71.MatCardModule,
              ([] as any[])),i0.ɵmpd(512,i72.CdkStepperModule,i72.CdkStepperModule,
              ([] as any[])),i0.ɵmpd(512,i35.MatIconModule,i35.MatIconModule,([] as any[])),
          i0.ɵmpd(512,i36.MatStepperModule,i36.MatStepperModule,([] as any[])),i0.ɵmpd(512,
              i73.LoginModule,i73.LoginModule,([] as any[])),i0.ɵmpd(512,i74.OrderRoutingModule,
              i74.OrderRoutingModule,([] as any[])),i0.ɵmpd(512,i75.MatCheckboxModule,
              i75.MatCheckboxModule,([] as any[])),i0.ɵmpd(512,i76.OrderModule,i76.OrderModule,
              ([] as any[])),i0.ɵmpd(512,i77.PipesModule,i77.PipesModule,([] as any[])),
          i0.ɵmpd(512,i40.CoreModule,i40.CoreModule,([] as any[])),i0.ɵmpd(512,i78.MatExpansionModule,
              i78.MatExpansionModule,([] as any[])),i0.ɵmpd(512,i31.MatLineModule,
              i31.MatLineModule,([] as any[])),i0.ɵmpd(512,i79.MatGridListModule,i79.MatGridListModule,
              ([] as any[])),i0.ɵmpd(512,i80.HomeRoutingModule,i80.HomeRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i81.HomeModule,i81.HomeModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
