/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ot-search[_ngcontent-%COMP%] {\n  padding: 15px 0px;\n  display: flex;\n  align-items: center;\n}\n.ot-search[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]{\n  margin-left: 10px;\n}\n.ot-search[_ngcontent-%COMP%]   .mat-form-field[_ngcontent-%COMP%] {\n  flex: 1;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLXRyYWNraW5nLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvb3JkZXIvb3JkZXItdHJhY2tpbmcvb3JkZXItdHJhY2tpbmcuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
