/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['$breakpoints[_ngcontent-%COMP%]:   ([_ngcontent-%COMP%]   xs[_ngcontent-%COMP%]:   0[_ngcontent-%COMP%], sm[_ngcontent-%COMP%]:   576px[_ngcontent-%COMP%], md[_ngcontent-%COMP%]:   768px[_ngcontent-%COMP%], lg[_ngcontent-%COMP%]:   992px[_ngcontent-%COMP%], xl[_ngcontent-%COMP%]:   1200px[_ngcontent-%COMP%], )[_ngcontent-%COMP%]   !default[_ngcontent-%COMP%];'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL3Nhc3MvX2JyZWFrcG9pbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9zYXNzL19icmVha3BvaW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
