/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home.module';
import * as i2 from './channel-intro/channel-intro.component.ngfactory';
import * as i3 from './embargo/embargo.component.ngfactory';
import * as i4 from './howtouse/howtouse.component.ngfactory';
import * as i5 from './faq/faq.component.ngfactory';
import * as i6 from './about/about.component.ngfactory';
import * as i7 from './terms/terms.component.ngfactory';
import * as i8 from './terms/terms-en/terms-en.component.ngfactory';
import * as i9 from './terms/appendix-limit/appendix-limit.component.ngfactory';
import * as i10 from './terms/appendix-ormd/appendix-ormd.component.ngfactory';
import * as i11 from './terms/insurance-intro/insurance-intro.component.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/cdk/bidi';
import * as i14 from '@angular/platform-browser';
import * as i15 from '@angular/cdk/platform';
import * as i16 from '@angular/cdk/a11y';
import * as i17 from '@angular/material/icon';
import * as i18 from '@angular/http';
import * as i19 from '@angular/material/stepper';
import * as i20 from '@angular/material/core';
import * as i21 from '@angular/cdk/collections';
import * as i22 from '@angular/cdk/observers';
import * as i23 from '@angular/cdk/scrolling';
import * as i24 from '@angular/cdk/portal';
import * as i25 from '@angular/material/button';
import * as i26 from '@angular/cdk/stepper';
import * as i27 from '@angular/material/expansion';
import * as i28 from '@angular/material/tabs';
import * as i29 from '@angular/material/grid-list';
import * as i30 from '@angular/router';
import * as i31 from './home-routing.module';
import * as i32 from './channel-intro/channel-intro.component';
import * as i33 from './embargo/embargo.component';
import * as i34 from './howtouse/howtouse.component';
import * as i35 from './faq/faq.component';
import * as i36 from './about/about.component';
import * as i37 from './terms/terms.component';
import * as i38 from './terms/terms-en/terms-en.component';
import * as i39 from './terms/appendix-limit/appendix-limit.component';
import * as i40 from './terms/appendix-ormd/appendix-ormd.component';
import * as i41 from './terms/insurance-intro/insurance-intro.component';
export const HomeModuleNgFactory:i0.NgModuleFactory<i1.HomeModule> = i0.ɵcmf(i1.HomeModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ChannelIntroComponentNgFactory,i3.EmbargoComponentNgFactory,i4.HowtouseComponentNgFactory,
              i5.FaqComponentNgFactory,i6.AboutComponentNgFactory,i7.TermsComponentNgFactory,
              i8.TermsEnComponentNgFactory,i9.AppendixLimitComponentNgFactory,i10.AppendixOrmdComponentNgFactory,
              i11.InsuranceIntroComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i12.NgLocalization,i12.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(6144,i13.DIR_DOCUMENT,(null as any),[i14.DOCUMENT]),
          i0.ɵmpd(4608,i13.Directionality,i13.Directionality,[[2,i13.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i15.Platform,i15.Platform,([] as any[])),i0.ɵmpd(4608,i16.InteractivityChecker,
              i16.InteractivityChecker,[i15.Platform]),i0.ɵmpd(4608,i16.FocusTrapFactory,
              i16.FocusTrapFactory,[i16.InteractivityChecker,i15.Platform,i0.NgZone]),
          i0.ɵmpd(136192,i16.AriaDescriber,i16.ARIA_DESCRIBER_PROVIDER_FACTORY,[[3,
              i16.AriaDescriber],i15.Platform]),i0.ɵmpd(5120,i16.LiveAnnouncer,i16.LIVE_ANNOUNCER_PROVIDER_FACTORY,
              [[3,i16.LiveAnnouncer],[2,i16.LIVE_ANNOUNCER_ELEMENT_TOKEN],i15.Platform]),
          i0.ɵmpd(5120,i16.FocusMonitor,i16.FOCUS_MONITOR_PROVIDER_FACTORY,[[3,i16.FocusMonitor],
              i0.NgZone,i15.Platform]),i0.ɵmpd(5120,i17.MatIconRegistry,i17.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i17.MatIconRegistry],[2,i18.Http],i14.DomSanitizer]),i0.ɵmpd(4608,
              i19.MatStepperIntl,i19.MatStepperIntl,([] as any[])),i0.ɵmpd(4608,i20.ErrorStateMatcher,
              i20.ErrorStateMatcher,([] as any[])),i0.ɵmpd(5120,i21.UniqueSelectionDispatcher,
              i21.ɵa,[[3,i21.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i22.MatMutationObserverFactory,
              i22.MatMutationObserverFactory,([] as any[])),i0.ɵmpd(5120,i23.ScrollDispatcher,
              i23.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i23.ScrollDispatcher],i0.NgZone,
                  i15.Platform]),i0.ɵmpd(5120,i23.ViewportRuler,i23.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i23.ViewportRuler],i15.Platform,i0.NgZone,i23.ScrollDispatcher]),
          i0.ɵmpd(512,i12.CommonModule,i12.CommonModule,([] as any[])),i0.ɵmpd(512,
              i20.CompatibilityModule,i20.CompatibilityModule,([] as any[])),i0.ɵmpd(512,
              i13.BidiModule,i13.BidiModule,([] as any[])),i0.ɵmpd(256,i20.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i20.MatCommonModule,i20.MatCommonModule,
              [[2,i20.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i24.PortalModule,i24.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i15.PlatformModule,i15.PlatformModule,([] as any[])),
          i0.ɵmpd(512,i20.MatRippleModule,i20.MatRippleModule,([] as any[])),i0.ɵmpd(512,
              i16.A11yModule,i16.A11yModule,([] as any[])),i0.ɵmpd(512,i25.MatButtonModule,
              i25.MatButtonModule,([] as any[])),i0.ɵmpd(512,i26.CdkStepperModule,
              i26.CdkStepperModule,([] as any[])),i0.ɵmpd(512,i17.MatIconModule,i17.MatIconModule,
              ([] as any[])),i0.ɵmpd(512,i19.MatStepperModule,i19.MatStepperModule,
              ([] as any[])),i0.ɵmpd(512,i27.MatExpansionModule,i27.MatExpansionModule,
              ([] as any[])),i0.ɵmpd(512,i22.ObserversModule,i22.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i23.ScrollDispatchModule,i23.ScrollDispatchModule,([] as any[])),
          i0.ɵmpd(512,i28.MatTabsModule,i28.MatTabsModule,([] as any[])),i0.ɵmpd(512,
              i20.MatLineModule,i20.MatLineModule,([] as any[])),i0.ɵmpd(512,i29.MatGridListModule,
              i29.MatGridListModule,([] as any[])),i0.ɵmpd(512,i30.RouterModule,i30.RouterModule,
              [[2,i30.ɵa],[2,i30.Router]]),i0.ɵmpd(512,i31.HomeRoutingModule,i31.HomeRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.HomeModule,i1.HomeModule,([] as any[])),
          i0.ɵmpd(1024,i30.ROUTES,() => {
            return [[{path:'channel-intro',component:i32.ChannelIntroComponent},{path:'embargo',
                component:i33.EmbargoComponent},{path:'howtouse',component:i34.HowtouseComponent},
                {path:'faq',component:i35.FaqComponent},{path:'about',component:i36.AboutComponent},
                {path:'terms',component:i37.TermsComponent},{path:'terms-en',component:i38.TermsEnComponent},
                {path:'appendix-limit',component:i39.AppendixLimitComponent},{path:'appendix-ormd',
                    component:i40.AppendixOrmdComponent},{path:'insurance-intro',component:i41.InsuranceIntroComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2hvbWUvaG9tZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvaG9tZS9ob21lLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
