/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home-routing.module';
import * as i2 from './channel-intro/channel-intro.component.ngfactory';
import * as i3 from './embargo/embargo.component.ngfactory';
import * as i4 from './howtouse/howtouse.component.ngfactory';
import * as i5 from './faq/faq.component.ngfactory';
import * as i6 from './about/about.component.ngfactory';
import * as i7 from './terms/terms.component.ngfactory';
import * as i8 from './terms/terms-en/terms-en.component.ngfactory';
import * as i9 from './terms/appendix-limit/appendix-limit.component.ngfactory';
import * as i10 from './terms/appendix-ormd/appendix-ormd.component.ngfactory';
import * as i11 from './terms/insurance-intro/insurance-intro.component.ngfactory';
import * as i12 from '@angular/router';
import * as i13 from './channel-intro/channel-intro.component';
import * as i14 from './embargo/embargo.component';
import * as i15 from './howtouse/howtouse.component';
import * as i16 from './faq/faq.component';
import * as i17 from './about/about.component';
import * as i18 from './terms/terms.component';
import * as i19 from './terms/terms-en/terms-en.component';
import * as i20 from './terms/appendix-limit/appendix-limit.component';
import * as i21 from './terms/appendix-ormd/appendix-ormd.component';
import * as i22 from './terms/insurance-intro/insurance-intro.component';
export const HomeRoutingModuleNgFactory:i0.NgModuleFactory<i1.HomeRoutingModule> = i0.ɵcmf(i1.HomeRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ChannelIntroComponentNgFactory,i3.EmbargoComponentNgFactory,i4.HowtouseComponentNgFactory,
              i5.FaqComponentNgFactory,i6.AboutComponentNgFactory,i7.TermsComponentNgFactory,
              i8.TermsEnComponentNgFactory,i9.AppendixLimitComponentNgFactory,i10.AppendixOrmdComponentNgFactory,
              i11.InsuranceIntroComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i12.RouterModule,i12.RouterModule,[[2,i12.ɵa],
          [2,i12.Router]]),i0.ɵmpd(512,i1.HomeRoutingModule,i1.HomeRoutingModule,([] as any[])),
          i0.ɵmpd(1024,i12.ROUTES,() => {
            return [[{path:'channel-intro',component:i13.ChannelIntroComponent},{path:'embargo',
                component:i14.EmbargoComponent},{path:'howtouse',component:i15.HowtouseComponent},
                {path:'faq',component:i16.FaqComponent},{path:'about',component:i17.AboutComponent},
                {path:'terms',component:i18.TermsComponent},{path:'terms-en',component:i19.TermsEnComponent},
                {path:'appendix-limit',component:i20.AppendixLimitComponent},{path:'appendix-ormd',
                    component:i21.AppendixOrmdComponent},{path:'insurance-intro',component:i22.InsuranceIntroComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2hvbWUvaG9tZS1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9ob21lL2hvbWUtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
