/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './core.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/http';
import * as i4 from './service/storage.service';
import * as i5 from './service/auth.service';
import * as i6 from '@angular/router';
import * as i7 from 'angular2-jwt/angular2-jwt';
import * as i8 from './service/common.service';
import * as i9 from './service/commonwx.service';
import * as i10 from './service/user.service';
import * as i11 from './service/guards/auth-guard.service';
import * as i12 from './service/order.service';
import * as i13 from './service/common-api.service';
import * as i14 from './service/pipes/pipes.module';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BrowserXhr,
          i3.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i3.ResponseOptions,i3.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i3.XSRFStrategy,i3.ɵb,([] as any[])),i0.ɵmpd(4608,
          i3.XHRBackend,i3.XHRBackend,[i3.BrowserXhr,i3.ResponseOptions,i3.XSRFStrategy]),
          i0.ɵmpd(4608,i3.RequestOptions,i3.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i3.Http,i3.ɵc,[i3.XHRBackend,i3.RequestOptions]),i0.ɵmpd(4608,i4.StorageService,
              i4.StorageService,([] as any[])),i0.ɵmpd(4608,i5.AuthService,i5.AuthService,
              [i4.StorageService,i6.Router]),i0.ɵmpd(5120,i7.AuthHttp,i1.authFactory,
              [i3.Http,i3.RequestOptions]),i0.ɵmpd(4608,i8.CommonService,i8.CommonService,
              [i3.Http,i7.AuthHttp,i5.AuthService]),i0.ɵmpd(4608,i9.CommonwxService,
              i9.CommonwxService,[i3.Http,i7.AuthHttp]),i0.ɵmpd(4608,i10.UserService,
              i10.UserService,[i8.CommonService,i9.CommonwxService]),i0.ɵmpd(4608,
              i11.AuthGuardService,i11.AuthGuardService,[i6.ActivatedRoute,i5.AuthService,
                  i10.UserService,i6.Router]),i0.ɵmpd(4608,i12.OrderService,i12.OrderService,
              [i8.CommonService]),i0.ɵmpd(4608,i13.CommonApiService,i13.CommonApiService,
              [i8.CommonService]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(512,i3.HttpModule,i3.HttpModule,([] as any[])),i0.ɵmpd(512,i14.PipesModule,
              i14.PipesModule,([] as any[])),i0.ɵmpd(512,i1.CoreModule,i1.CoreModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vd29ya3N0YXRpb24vd2VpeGluLWN1bC93ZWl4aW4tY3Vsd2ViL3NyYy9hcHAvY29yZS9jb3JlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
