/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.otd-info[_ngcontent-%COMP%] {\n    display: flex;\n    align-items: center;\n    padding: 10px;\n    background-color: #ffffff;\n    margin: 10px 0px;\n  }\n  .otd-info[_ngcontent-%COMP%]   img[_ngcontent-%COMP%]{\n    width: 80px;\n    padding-right: 10px;\n  }\n  .otd-info[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{\n    color: #6dca8c;\n    font-size: 18px;\n    margin: 5px;\n  }\n  .otd-info[_ngcontent-%COMP%]   span[_ngcontent-%COMP%]{\n    color: #999999;\n    font-size: 14px;\n    margin: 5px;\n  }\n  .otd-tracking[_ngcontent-%COMP%]   .mat-step-icon[_ngcontent-%COMP%]   .mat-icon[_ngcontent-%COMP%] {\n    display: none !important;\n  }\n  .otd-tracking[_ngcontent-%COMP%]   .mat-step-icon[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] {\n    display: none !important;\n  }\n  .mat-vertical-stepper-header[_ngcontent-%COMP%]{\n    pointer-events: none !important;\n  }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3dvcmtzdGF0aW9uL3dlaXhpbi1jdWwvd2VpeGluLWN1bHdlYi9zcmMvYXBwL29yZGVyL29yZGVyLXRyYWNraW5nL29yZGVyLXRyYWNraW5nLWRldGFpbC9vcmRlci10cmFja2luZy1kZXRhaWwuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy93b3Jrc3RhdGlvbi93ZWl4aW4tY3VsL3dlaXhpbi1jdWx3ZWIvc3JjL2FwcC9vcmRlci9vcmRlci10cmFja2luZy9vcmRlci10cmFja2luZy1kZXRhaWwvb3JkZXItdHJhY2tpbmctZGV0YWlsLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
